### ISSUE TITLE
Bank Notify

### ISSUE THREAD

**Issue by baylordevelopments** [boiidevelopment/boii_ui#1]
When walking up to the bank, it spams the notify
![boii_ui](https://github.com/boiidevelopment/boii_ui/assets/107185042/8faa6961-eb42-496f-89c6-c7a6e35193d5)

**Comment by CaseIRL** [comment]
fixed https://github.com/boiidevelopment/boii_ui/commit/9d9a647f8abd78c6e5f2aa65ce71da29c1bcf69b
